
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLOR COMENTARIO COORDENADAS END_PRINT NEW_PRINT SET_PRINT_ESTRELLA SET_PRINT_O SET_PRINT_TRIANGULO SET_PRINT_Xinicio : comentario inicio\n              | impresion inicio\n              | sets_print inicio\n              |impresion : NEW_PRINTsets_print : SET_PRINT_X\n                  | SET_PRINT_O\n                  | SET_PRINT_TRIANGULO\n                  | SET_PRINT_ESTRELLAcomentario : COMENTARIO'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[-4,0,-4,-4,-4,-10,-5,-6,-7,-8,-9,-1,-2,-3,]),'COMENTARIO':([0,2,3,4,5,6,7,8,9,10,],[5,5,5,5,-10,-5,-6,-7,-8,-9,]),'NEW_PRINT':([0,2,3,4,5,6,7,8,9,10,],[6,6,6,6,-10,-5,-6,-7,-8,-9,]),'SET_PRINT_X':([0,2,3,4,5,6,7,8,9,10,],[7,7,7,7,-10,-5,-6,-7,-8,-9,]),'SET_PRINT_O':([0,2,3,4,5,6,7,8,9,10,],[8,8,8,8,-10,-5,-6,-7,-8,-9,]),'SET_PRINT_TRIANGULO':([0,2,3,4,5,6,7,8,9,10,],[9,9,9,9,-10,-5,-6,-7,-8,-9,]),'SET_PRINT_ESTRELLA':([0,2,3,4,5,6,7,8,9,10,],[10,10,10,10,-10,-5,-6,-7,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,2,3,4,],[1,11,12,13,]),'comentario':([0,2,3,4,],[2,2,2,2,]),'impresion':([0,2,3,4,],[3,3,3,3,]),'sets_print':([0,2,3,4,],[4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> comentario inicio','inicio',2,'p_inicio','analizador.py',41),
  ('inicio -> impresion inicio','inicio',2,'p_inicio','analizador.py',42),
  ('inicio -> sets_print inicio','inicio',2,'p_inicio','analizador.py',43),
  ('inicio -> <empty>','inicio',0,'p_inicio','analizador.py',44),
  ('impresion -> NEW_PRINT','impresion',1,'p_impresion','analizador.py',48),
  ('sets_print -> SET_PRINT_X','sets_print',1,'p_sets_print','analizador.py',52),
  ('sets_print -> SET_PRINT_O','sets_print',1,'p_sets_print','analizador.py',53),
  ('sets_print -> SET_PRINT_TRIANGULO','sets_print',1,'p_sets_print','analizador.py',54),
  ('sets_print -> SET_PRINT_ESTRELLA','sets_print',1,'p_sets_print','analizador.py',55),
  ('comentario -> COMENTARIO','comentario',1,'p_comentario','analizador.py',59),
]
